# Generated by Django 4.0 on 2021-12-19 16:04

import data_view.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='immo_bienny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lot', models.CharField(max_length=255, verbose_name='id_lot')),
                ('nb_piece', models.IntegerField(verbose_name='nb_piece')),
                ('typologie', models.CharField(blank=True, default='', max_length=150, verbose_name='typologie')),
                ('prix_tva_reduite', models.FloatField(verbose_name='prix_tva_reduite')),
                ('prix_tva_normale', models.FloatField(verbose_name='prix_tva_normale')),
                ('prix_HT', models.FloatField(verbose_name='prix_HT')),
                ('prix_m2_HT', models.FloatField(verbose_name='prix_m2_HT')),
                ('prix_m2_TTC', models.FloatField(verbose_name='prix_m2_TTC')),
                ('surface', models.FloatField(verbose_name='surface')),
                ('etage', models.IntegerField(verbose_name='etage')),
                ('orientation', models.CharField(blank=True, default='', max_length=30, verbose_name='orientation')),
                ('exterieur', models.BooleanField(verbose_name='exterieur')),
                ('balcony', data_view.models.CustomBooleanField(default=1, verbose_name='balcony')),
                ('garden', models.BooleanField(verbose_name='garden')),
                ('parking', models.BooleanField(verbose_name='parking')),
                ('nom_programme', models.CharField(blank=True, default='', max_length=100, verbose_name='nom_programme')),
                ('ville', models.CharField(blank=True, default='', max_length=150, verbose_name='ville')),
                ('departement', models.IntegerField(verbose_name='departement')),
                ('date_fin_programme', models.TextField(verbose_name='date_fin_programme ')),
                ('adresse_entiere', models.TextField(max_length=150, verbose_name='adresse_entiere')),
                ('promoteur', models.CharField(blank=True, default='', max_length=150, verbose_name='promoteur')),
                ('date_extraction', models.TextField(verbose_name='date_extraction')),
            ],
            options={
                'db_table': 'immo_bienny',
            },
        ),
        migrations.AddConstraint(
            model_name='immo_bienny',
            constraint=models.UniqueConstraint(fields=('id_lot', 'nb_piece', 'typologie', 'prix_tva_reduite', 'prix_tva_normale', 'prix_HT', 'prix_m2_HT', 'prix_m2_TTC', 'surface', 'etage', 'orientation', 'exterieur', 'balcony', 'garden', 'parking', 'nom_programme', 'ville', 'departement', 'date_fin_programme', 'adresse_entiere', 'promoteur', 'date_extraction'), name='unique_immo_name'),
        ),
    ]
